# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a461011c831dfe2d5b6dace31c3e7361f842c293494eb53ad561f50d475fac65ae48f79b5242681f700e3afbc943c5aaff84e22fce913e844d9b27a9ac0e270c

test:
  secret_key_base: 5724d98c6c1c811071e5a59ba5558e90685b52033787b2ecb1b44d279f33758174345e0a91f22ecaad290188f36090bc094bc1e6cfd024c4fec085e10ef260ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
